---
# file: roles/hadoop_pseudo/handlers/main.yml
- name: hadoop hdfs service restart
  service: name={{item}} state=restarted
  with_items:
    - hadoop-hdfs-namenode
    - hadoop-hdfs-secondarynamenode
    - hadoop-hdfs-datanode

- name: hadoop yarn service restart
  service: name={{item}} state=restarted
  with_items:
    - hadoop-yarn-resourcemanager
    - hadoop-yarn-nodemanager
    - hadoop-mapreduce-historyserver

- name: postgresql restart
  service: name={{item}} state=restarted
  with_items:
    - postgresql

- name: restart hive
  service: name={{item}} state=restarted
  with_items:
    - hive-metastore
    - hive-server2
    - hive-server

- name: impala restart
  service: name={{item}} state=restarted
  with_items:
    - impala-server
    - impala-state-store
    - impala-catalog

- name: netfs rechkconfig
  shell: chkconfig netfs off && chkconfig netfs on

