---
# file: roles/hadoop_pseudo/handlers/main.yml
- name: postgresql restart
  service: name={{item}} state=restarted
  with_items:
    - postgresql

- name: restart hive
  service: name={{item}} state=restarted
  with_items:
    - hive-metastore
    - hive-server2
    - hive-server

- name: restart impala
  service: name={{item}} state=restarted
  with_items:
    - impala-server
    - impala-state-store
    - impala-catalog
