---
# file: roles/hadoop_pseudo/handlers/main.yml
- name: postgresql restart
  service: name={{item}} state=restarted
  with_items:
    - postgresql

- name: restart hive
  service: name={{item}} state=restarted
  with_items:
    - hive-metastore

