---
# file: roles/common/handlers/main.yml
- name: ntpd start
  service: name=ntpd state=started enabled=yes

- name: restart ntpd
  service: name=ntpd state=restarted

- name: restart iptables
  service: name=iptables state=restarted
