---
# file: roles/hadoop_pesudo/tasks/main.yml

- name: Oracle JDK install check
  command: rpm -q jdk
  register: inst_jdk
  failed_when: inst_jdk.rc not in [0,1]
  changed_when: inst_jdk.rc != 0
  notify:
    - copy Oracle JDK
    - Oracle JDK install

- name: Add hadoop group
  group:
    name={{item.group}}
    gid={{item.gid}}
  with_items: hadoop_user

- name: Add hadoop user
  user:
    name="{{item.name}}"
    password="{{item.password}}"
    uid="{{item.uid}}"
    group="{{item.group}}"
    comment="{{item.name}}"
  with_items: hadoop_user

- name: Add a Cloudera reposigory key
  rpm_key:
    key=http://archive.cloudera.com/cdh5/redhat/6/x86_64/cdh/RPM-GPG-KEY-cloudera
    state=present

- name: install CDH5 package
  yum:
    name=http://archive.cloudera.com/cdh5/one-click-install/redhat/6/x86_64/cloudera-cdh-5-0.x86_64.rpm
    state=present

- name: cdh packages install
  yum: name={{item}} state=present
  with_items:
    - hadoop-conf-pseudo
    - hive
    - hive-metastore
    - hive-server2
    - zookeeper-server

- name: postgresql package install
  yum: name={{item}} state=present
  with_items:
    - postgresql-server
    - postgresql-devel
    - postgresql-jdbc
    - python-psycopg2

- name: postgresql initdb
  command: service postgresql initdb creates=/var/lib/pgsql/data/PG_VERSION

- name: postgresql.conf update
  template: src=postgresql.conf.j2 dest=/var/lib/pgsql/data/postgresql.conf owner=postgres group=postgres mode=600
  notify: postgresql restart

- name: postgresql access permissions
  template: src=pg_hba.conf.j2 dest=/var/lib/pgsql/data/pg_hba.conf owner=postgres group=postgres mode=600
  notify: postgresql restart

- name: postgresql start
  service: name={{item}} state=started enabled=yes
  with_items:
    - postgresql

- name: jdbc setup for hive
  file: src=/usr/share/java/postgresql-jdbc.jar dest=/usr/lib/hive/lib/postgresql-jdbc.jar state=link

- name: zookeeper-server init
  command: service zookeeper-server init creates=/var/lib/zookeeper/version-2

- name: zookeeper start
  service: name={{item}} state=started enabled=yes
  with_items:
    - zookeeper-server

- name: hive db user create
  postgresql_user:
    name="hiveuser"
    password="hadoop123"
    login_host=127.0.0.1
    role_attr_flags=CREATEDB,CREATEROLE,SUPERUSER

- name: hive db create
  postgresql_db:
    name=metastore
    owner=hiveuser
    login_host=127.0.0.1
  notify: create hive schema

- name: hive-site.xml update
  template: src=hive-site.xml.j2 dest=/etc/hive/conf/hive-site.xml owner=root group=root mode=644
  notify: restart hive

- name: hive service
  service: name={{item}} state=started enabled=yes
  with_items:
    - hive-metastore
