---
# file: roles/docker/tasks/main.yml
- name: install epel
  yum:
    name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
    state=present

- name: docker install
  yum: name={{item}} state=present
  with_items:
    - docker-io

- name: ifcfg settings.
  template: src={{item}}.j2 dest=/etc/sysconfig/network-scripts/{{item}} owner=root group=root mode=755
  with_items:
    - ifcfg-br0
    - ifcfg-eth0
  notify: network restart
